spring: 
  profiles: 
   active: 
   - dev 
---
spring: 
  profiles: dev
  application:
    name: microservicecloud-config-changping-dev  #应用名不能有下划线
---
spring: 
  profiles: test
  application:
    name: microservicecloud-config-changping-test  #应用名不能有下划线
    
#必须保存为UTF-8格式，否则，传到github后与本地项目不兼容